workflows:
  ios-appstore:
    name: iOS App Store Build
    integrations:
      app_store_connect: Coda3  # имя ключа в Codemagic Integrations

    environment:
      vars:
        XCODE_PROJECT: "AlarmApp.xcodeproj"
        XCODE_SCHEME: "AlarmApp"
        BUNDLE_ID: "com.serhiitkachuk.AlarmApp"
        DEV_TEAM: "CW6VS28729"

    scripts:
      # 1) Тянем/создаём профили и ставим сертификаты в кейчейн
      - name: Fetch signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain use-signing-files
          xcode-project use-profiles

      # 2) Архивируем (используем generic iOS destination, чтобы Xcode не лез на "My Mac")
      - name: Build archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            archive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive

      # 3) Экспортируем .ipa
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/ios_app.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
