workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_WORKSPACE: "AlarmApp.xcodeproj"
        XCODE_SCHEME: "AlarmApp"
        BUNDLE_ID: "com.serhiitkachuk.AlarmApp"
        DEVELOPMENT_TEAM: "CW6VS28729"
        PROVISIONING_PROFILE_SPECIFIER: "alarmapp_appstore_profile"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.serhiitkachuk.AlarmApp"
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods || true
          pod install || true

      - name: Build archive
        script: |
          xcodebuild archive \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_SPECIFIER \
            CODE_SIGN_STYLE=Manual

      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/ios_app.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        integration: appstore_integration   # имя интеграции в Codemagic
        submit_to_testflight: true
        submit_to_app_store: false
