workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      groups:
        - app_store
      vars:
        XCODE_PROJECT: "AlarmApp.xcodeproj"
        XCODE_SCHEME: "AlarmApp"
        BUNDLE_ID: "com.serhiitkachuk.AlarmApp"
        DEV_TEAM: "CW6VS28729"
        PROVISIONING_PROFILE_SPECIFIER: "alarmapp_appstore_profile"
    scripts:
      - name: Build archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            DEVELOPMENT_TEAM="$DEV_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            CODE_SIGN_STYLE=Manual \
            archive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive

      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/ios_app.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
