workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_WORKSPACE: "AlarmApp.xcodeproj"
        XCODE_SCHEME: "AlarmApp"
        BUNDLE_ID: "com.serhiitkachuk.AlarmApp"
        DEVELOPMENT_TEAM: "CW6VS28729"
        PROVISIONING_PROFILE_SPECIFIER: "alarmapp_appstore_profile"
      xcode: 16.4
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods --no-document
          pod install
      - name: Build archive
        script: |
          xcodebuild -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            clean archive | xcpretty
    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/ios_app.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
