workflows:
  ios-appstore:
    name: iOS App Store Build
    integrations:
      app_store_connect: Coda3   # имя твоего API ключа в Codemagic

    environment:
      vars:
        XCODE_PROJECT: "AlarmApp.xcodeproj"
        XCODE_SCHEME: "AlarmApp"
        BUNDLE_ID: "com.serhiitkachuk.AlarmApp"
        DEV_TEAM: "CW6VS28729"

    scripts:
      # 1) Подтягиваем сертификаты и provisioning profiles из Apple Developer
      - name: Fetch signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain use-signing-files
          xcode-project use-profiles

      # 2) Архивируем iOS приложение (автоматическая подпись)
      - name: Build archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            DEVELOPMENT_TEAM="$DEV_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates

      # 3) Экспортируем IPA для TestFlight/App Store
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/ios_app.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
