workflows:
  ios-appstore:
    name: iOS App Store Build
    max_build_duration: 120
    integrations:
      app_store_connect: integration
    environment:
      vars:
        XCODE_PROJECT: "AlarmApp.xcodeproj"
        XCODE_SCHEME: "AlarmApp"
        BUNDLE_ID: "com.serhiitkachuk.AlarmApp"
        TEAM_ID: "CW6VS28729"
    scripts:
      - name: Set up signing
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            "$BUNDLE_ID"
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: |
          set -e
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            DEVELOPMENT_TEAM=$TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            archive -archivePath $CM_BUILD_DIR/ios/archive/AlarmApp.xcarchive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios/archive/AlarmApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios/ipa
    artifacts:
      - ios/ipa/*.ipa
      - ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
