workflows:
  ios-appstore:
    name: iOS App Store Workflow
    environment:
      groups:
        - app_store   # подключение группы с ключами
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods --user-install
          pod install --project-directory=AlarmApp || true

      - name: Build iOS App
        script: |
          xcodebuild \
            -project AlarmApp.xcodeproj \
            -scheme AlarmApp \
            -sdk iphoneos \
            -configuration Release \
            clean archive \
            -archivePath $CM_BUILD_DIR/AlarmApp.xcarchive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/AlarmApp.xcarchive \
            -exportOptionsPlist AlarmApp/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/AlarmApp.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_content: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_app_store: true
        submit_to_testflight: true
