workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_WORKSPACE: "AlarmApp.xcworkspace"
        XCODE_SCHEME: "AlarmApp"
      ios_signing:
        provisioning_profiles:
          - alarmapp_appstore_profile
        development_team: CW6VS28729

    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/AlarmApp.xcarchive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER=alarmapp_appstore_profile \
            archive
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/AlarmApp.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist ExportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/ipa/*.dSYM.zip
      - $CM_BUILD_DIR/ipa/*.plist

    publishing:
      app_store_connect:
        integration: Coda3
