workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      groups:
        - app_store
    scripts:
      - name: Build archive
        script: |
          xcodebuild \
            -project AlarmApp.xcodeproj \
            -scheme AlarmApp \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/*.dSYM.zip
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
