workflows:
  ios-appstore:
    name: iOS App Store Build

    integrations:
      app_store_connect: Coda3   # имя интеграции из Codemagic UI

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.serhiitkachuk.AlarmApp
        provisioning_profiles:
          - alarmapp_appstore_profile

    scripts:
      - name: Build archive
        script: |
          xcodebuild \
            -project AlarmApp.xcodeproj \
            -scheme AlarmApp \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            DEVELOPMENT_TEAM=CW6VS28729 \
            PRODUCT_BUNDLE_IDENTIFIER=com.serhiitkachuk.AlarmApp \
            PROVISIONING_PROFILE_SPECIFIER=alarmapp_appstore_profile \
            archive

      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/ios_app.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
