workflows:
  ios-appstore:
    name: iOS App Store Build
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.serhiitkachuk.AlarmApp"
      vars:
        XCODE_PROJECT: "AlarmApp.xcodeproj"
        XCODE_SCHEME: "AlarmApp"
        BUNDLE_ID: "com.serhiitkachuk.AlarmApp"
        TEAM_ID: "CW6VS28729"
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods --no-document
      - name: Build IPA
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            archive -archivePath $CM_BUILD_DIR/ios/archive/AlarmApp.xcarchive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios/archive/AlarmApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios/ipa
    artifacts:
      - ios/ipa/*.ipa
      - ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
