scripts:
  - name: Build for simulator
    script: |
      xcodebuild \
        -project AlarmApp.xcodeproj \
        -scheme AlarmApp \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14' \
        build
